export const countries = [
  "Australia",
  "Canada",
  "China",
  "Germany",
  "India",
  "Japan",
  "Malaysia",
  "Netherlands",
  "Philippines",
  "Saudi Arabia",
  "Singapore",
  "South Korea",
  "Thailand",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vietnam",
  "Other",
];